version: "3.8"

services:
  micropython:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: v1.22.0
        PORT: ${PORT}
        BOARD: ${BOARD}
        USER_C_MODULES: ${USER_C_MODULES}
    volumes:
      - ./build:/root/build
      - ./modules:/modules
    environment:
      DEBIAN_FRONTEND: noninteractive
